insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (1,'2010-09-07','COMPLEX','Macbook PRO Retina')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (2,'2011-02-13','SIMPLE','Samsung LED')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (3,'2011-03-10','SIMPLE','Nokia Lumia')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (4,'2012-03-29','SIMPLE','HTC ONE')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (5,'2012-04-03','SIMPLE','Samsung Galaxy 4')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (6,'2012-05-02','SIMPLE','Macbook Air 13')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (7,'2012-06-24','COMPLEX','Motorola')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (8,'2012-07-05','SIMPLE','Nokia 3310 + Ladowarka')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (9,'2012-08-21','SIMPLE','HP Probook')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (10,'2012-10-16','COMPLEX','Lenovo X1 Carbon')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (11,'2012-11-06','COMPLEX','HP EliteBook')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (12,'2012-12-31','SIMPLE','Samsung ultrabook')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (13,'2013-01-15','SIMPLE','BMW 330')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (14,'2013-01-16','COMPLEX','Mercedes C-Klasa')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (15,'2013-01-17','COMPLEX','VW Golf 7')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (16,'2013-02-01','SIMPLE','Fiat 125p')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (17,'2013-02-03','COMPLEX','Rover 220 SDI')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (18,'2013-02-10','COMPLEX','Renault Megane Coupe')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (19,'2013-03-20','SIMPLE','BMW X5')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (20,'2013-03-26','SIMPLE','Audi Q7')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (21,'2013-04-07','COMPLEX','Hummer H3')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (22,'2013-05-10','SIMPLE','Porsche Carrera')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (23,'2013-05-11','COMPLEX','Toyota Supra')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (24,'2013-05-13','SIMPLE','Desing Patterns GOF')
insert into DB_ORDER (ID, CREATE_DATE, TYPE,SERVICE_NAME) values (25,'2013-06-01','COMPLEX','Refactoring to patterns')

